//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionManager.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DomainMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubscriptionManager.Domain.Resources.DomainMessages", typeof(DomainMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O contrato já está cancelado..
        /// </summary>
        internal static string ContractAlreadyCancelled {
            get {
                return ResourceManager.GetString("ContractAlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O contrato não está suspenso e não pode ser ativado..
        /// </summary>
        internal static string ContractCannotBeReactivated {
            get {
                return ResourceManager.GetString("ContractCannotBeReactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O contrato não está ativo e não pode ser suspenso..
        /// </summary>
        internal static string ContractCannotBeSuspended {
            get {
                return ResourceManager.GetString("ContractCannotBeSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Customer ID não pode ser vazio.
        /// </summary>
        internal static string ContractCustomerIdRequired {
            get {
                return ResourceManager.GetString("ContractCustomerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plan ID não pode ser vazio.
        /// </summary>
        internal static string ContractPlanIdRequired {
            get {
                return ResourceManager.GetString("ContractPlanIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O documento não pode ser nulo ou conter apenas espaços em branco..
        /// </summary>
        internal static string DocumentRequired {
            get {
                return ResourceManager.GetString("DocumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email deve conter o caractere &apos;@&apos;..
        /// </summary>
        internal static string EmailMustContainAtSign {
            get {
                return ResourceManager.GetString("EmailMustContainAtSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail não pode ser nulo ou conter apenas espaços em branco..
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor da fatura não pode ser menor ou igual a zero..
        /// </summary>
        internal static string InvoiceAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("InvoiceAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor da fatura não pode ser nulo..
        /// </summary>
        internal static string InvoiceAmountRequired {
            get {
                return ResourceManager.GetString("InvoiceAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A fatura não está em um estado válido para ser cancelada..
        /// </summary>
        internal static string InvoiceCannotBeCancelled {
            get {
                return ResourceManager.GetString("InvoiceCannotBeCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A fatura não está em um estado válido para ser marcada como vencida..
        /// </summary>
        internal static string InvoiceCannotBeMarkedAsOverdue {
            get {
                return ResourceManager.GetString("InvoiceCannotBeMarkedAsOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A fatura não está em um estado válido para ser paga..
        /// </summary>
        internal static string InvoiceCannotBePaid {
            get {
                return ResourceManager.GetString("InvoiceCannotBePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A fatura não está em um estado válido para ser reembolsada..
        /// </summary>
        internal static string InvoiceCannotBeRefunded {
            get {
                return ResourceManager.GetString("InvoiceCannotBeRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O identificador do contrato não pode ser vazio..
        /// </summary>
        internal static string InvoiceContractIdRequired {
            get {
                return ResourceManager.GetString("InvoiceContractIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor não pode ser negativo..
        /// </summary>
        internal static string MoneyAmountCannotBeNegative {
            get {
                return ResourceManager.GetString("MoneyAmountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor não pode ser nulo..
        /// </summary>
        internal static string MoneyAmountRequired {
            get {
                return ResourceManager.GetString("MoneyAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome não pode ser nulo ou conter apenas espaços em branco..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O plano já está desativado..
        /// </summary>
        internal static string PlanAlreadyInactive {
            get {
                return ResourceManager.GetString("PlanAlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O preço mensal deve ser maior que zero..
        /// </summary>
        internal static string PlanMonthlyPriceMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PlanMonthlyPriceMustBeGreaterThanZero", resourceCulture);
            }
        }
    }
}
